sudo: required
language: rust
rust:
  - stable
  - beta
branches:
  only:
  - master
  - "/^v\\d+\\./"
os:
- linux

script:
- pushd ./backend
- cargo build --verbose
- pushd ./renderer && pwd && cargo test --lib && popd
- pushd ./server && pwd && cargo test --lib && popd
- popd

notifications:
- email: false
