sudo: required
language: rust
rust:
  - stable
  - beta
branches:
  only:
  - master
  - "/^v\\d+\\./"
os:
- linux

script:
- cd backend
- cargo build --verbose
- cargo test --verbose

notifications:
- email: false
